GET https://bennihirokugis.herokuapp.com/addUrl?url=https://i.pinimg.com/564x/7a/ff/9e/7aff9e3e3c32330d68d52184afdef645.jpg&name=pic_28

###

GET https://bennihirokugis.herokuapp.com/getUrl

###

GET https://bennihirokugis.herokuapp.com/removeUrl?url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FImage%23%2Fmedia%2FFile%3AImage_created_with_a_mobile_phone.png

###

GET https://bennihirokugis.herokuapp.com/addScore?name=XY&time=20.455

###
GET https://bennihirokugis.herokuapp.com/getScore

###
GET https://bennihirokugis.herokuapp.com/addUrl?url=https://cdn.discordapp.com/emojis/740671692543623219.png?v=1&name=pic_2

###
GET https://bennihirokugis.herokuapp.com/addUrl?url=https://cdn.discordapp.com/emojis/762522595366666300.png?v=1&name=pic_3

###

GET https://bennihirokugis.herokuapp.com/addUrl?url=https://cdn.discordapp.com/emojis/793222401050542169.png?v=1&name=pic_10